"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { request } from "@/lib/api";
import type { AnalysisResponse, AnalysisType } from "@/lib/types";
const labels: Record<AnalysisType,string>={market:"Market intelligence",competitor:"Competitor intelligence",trend:"Trend discovery",swot:"SWOT analysis"};
export function ResearchInputForm() {
 const router=useRouter(); const [type,setType]=useState<AnalysisType>("market"); const [industry,setIndustry]=useState(""); const [idea,setIdea]=useState(""); const [competitors,setCompetitors]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const path=type==="market"?"/market/analyze":type==="competitor"?"/competitor/analyze":type==="trend"?"/trends/discover":"/swot/analyze"; const body=type==="swot"?{user_id:"workspace-user",startup_concept:idea}:type==="competitor"?{user_id:"workspace-user",industry,competitor_names:competitors.split(",").map(x=>x.trim()).filter(Boolean)}:type==="market"?{user_id:"workspace-user",industry,startup_idea:idea}:{user_id:"workspace-user",industry}; const result=await request<AnalysisResponse>(path,{method:"POST",body:JSON.stringify(body)}); router.push(`/analysis/${result.report_id}`)}catch(err){setError(err instanceof Error?err.message:"Research could not start")}finally{setBusy(false)}}
 return <main className="shell"><nav className="nav"><span className="brand">STARTUP INTELLIGENCE</span><span className="eyebrow">New research</span></nav><div style={{maxWidth:760,margin:"56px auto"}}><p className="eyebrow">Research brief</p><h1>Frame the question.</h1><p className="muted">Choose a research lens and provide only the context an analyst needs.</p><form className="panel" onSubmit={submit} style={{marginTop:28}}><div className="grid"><div className="field"><label>Research type</label><select value={type} onChange={e=>setType(e.target.value as AnalysisType)}>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div>{type!=="swot"&&<div className="field"><label>Industry</label><input required value={industry} onChange={e=>setIndustry(e.target.value)} placeholder="e.g. Climate software"/></div>}</div>{type!=="trend"&&<div className="field" style={{marginTop:16}}><label>{type==="swot"?"Startup concept":"Startup idea"}</label><textarea required value={idea} onChange={e=>setIdea(e.target.value)} placeholder="Describe the concept, context, and intended customer."/></div>}{type==="competitor"&&<div className="field" style={{marginTop:16}}><label>Competitors</label><input required value={competitors} onChange={e=>setCompetitors(e.target.value)} placeholder="Comma-separated company names"/></div>}{error&&<p className="error">{error}</p>}<button className="button" disabled={busy} style={{marginTop:24}}>{busy?"Running research…":"Generate research"}</button></form></div></main>;
}
